name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          

      - name: Run tests
        run: python -m unittest discover

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t divyanshu157/hello-world-cicd:latest .

      - name: Run Docker container
        run: docker run --name hello-world-container -d divyanshu157/hello-world-cicd:latest

      - name: Test Docker container
        run: |
          sleep 5
          docker logs hello-world-container

      - name: Push Docker image
        run: docker push divyanshu157/hello-world-cicd:latest

      - name: Clean up
        run: docker rm -f hello-world-container
